/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AssetFontPreview: typeof import('./components/AssetFontPreview.vue')['default']
    AssetImage: typeof import('./components/AssetImage.vue')['default']
    AssetInfo: typeof import('./components/AssetInfo.vue')['default']
    AssetPreview: typeof import('./components/AssetPreview.vue')['default']
    DrakToggle: typeof import('./components/DrakToggle.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    Panel: typeof import('./components/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Serach: typeof import('./components/Serach.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
  }
}
