/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./components/a.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    DrakToggle: typeof import('./components/DrakToggle.vue')['default']
    ItemImage: typeof import('./components/ItemImage.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Serach: typeof import('./components/Serach.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
  }
}
